/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/me": {
    /**
     * Read Users Me
     * @description Mengambil data profil lengkap (User model) untuk pengguna yang saat ini terotentikasi.
     *
     * INPUT: None (Otentikasi melalui header JWT).
     * OUTPUT: User (ID, email, nama, subscription_tier).
     *
     * KAPAN DIGUNAKAN: Dipanggil saat inisialisasi aplikasi atau setelah login/refresh sesi untuk memverifikasi keaktifan sesi dan memuat detail pengguna ke UI.
     */
    get: operations["read_users_me_api_v1_auth_me_get"];
    /**
     * Update Users Me
     * @description Memperbarui atribut tertentu dari profil pengguna yang sedang login (nama, email, metadata).
     *
     * INPUT: UserUpdate (Opsional: name, email, metadata: {phone_number: str}).
     * OUTPUT: User (Objek pengguna yang telah diperbarui).
     *
     * KAPAN DIGUNAKAN: Di halaman 'Settings' pengguna saat memperbarui informasi profil. Memerlukan sinkronisasi antara tabel 'auth.users' dan 'public.Users'.
     */
    patch: operations["update_users_me_api_v1_auth_me_patch"];
  };
  "/api/v1/auth/refresh": {
    /**
     * Refresh JWT access token
     * @description Refresh JWT access token using a valid refresh token.
     *
     * This endpoint exchanges a valid refresh token for a new JWT access token.
     * The refresh token must be valid and not expired.
     */
    post: operations["refresh_access_token_api_v1_auth_refresh_post"];
  };
  "/api/v1/blocks/": {
    /**
     * List Blocks In Canvas Endpoint
     * @description Endpoint untuk mengambil semua block dalam sebuah canvas.
     */
    get: operations["list_blocks_in_canvas_endpoint_api_v1_blocks__get"];
    /**
     * Create New Block Endpoint
     * @description Endpoint untuk membuat block baru. Meneruskan user_id (created_by) untuk audit.
     */
    post: operations["create_new_block_endpoint_api_v1_blocks__post"];
  };
  "/api/v1/blocks/{block_id}": {
    /**
     * Delete A Block Endpoint
     * @description Endpoint untuk menghapus block beserta embeddingnya.
     */
    delete: operations["delete_a_block_endpoint_api_v1_blocks__block_id__delete"];
    /**
     * Update Block Content Endpoint
     * @description Endpoint untuk memperbarui block. Meneruskan user_id (updated_by) untuk audit.
     */
    patch: operations["update_block_content_endpoint_api_v1_blocks__block_id__patch"];
  };
  "/api/v1/calendars/calendars/": {
    /**
     * List Kalender Saya (yang di-subscribe)
     * @description Mengambil daftar semua kalender yang di-subscribe oleh pengguna.
     *
     * Fitur:
     * Ini mengembalikan 'role' pengguna di kalender tersebut
     * beserta detail kalendernya (JOIN).
     */
    get: operations["get_my_subscribed_calendars_api_v1_calendars_calendars__get"];
    /**
     * Buat Kalender Baru
     * @description Membuat "wadah" kalender baru. Pembuat otomatis ditambahkan sebagai 'owner'
     *
     * Fitur:
     * - Jika 'workspace_id' disediakan, kalender ini milik workspace.
     * - Jika tidak, kalender ini bersifat pribadi ('owner_user_id' diisi otomatis).
     * - Pembuat otomatis ditambahkan sebagai 'owner' di 'CalendarSubscriptions'.
     *
     * INPUT: CalendarCreate (name: str, workspace_id: Optional[UUID]).
     * OUTPUT: Calendar (ID, name, owner/workspace ID).
     *
     * KAPAN DIGUNAKAN: Di UI Kalender saat pengguna membuat kalender baru.
     */
    post: operations["create_new_calendar_api_v1_calendars_calendars__post"];
  };
  "/api/v1/calendars/calendars/{calendar_id}": {
    /**
     * Hapus Kalender
     * @description Menghapus kalender secara permanen.
     *
     * Fitur:
     * Semua 'Subscriptions', 'Schedules', dan 'Instances' terkait
     * akan dihapus oleh 'ON DELETE CASCADE' di database.
     *
     * Keamanan:
     * Hanya 'owner' atau 'editor' (sesuai 'get_calendar_editor_access').
     * (Kita mungkin perlu memperketat ini HANYA untuk 'owner' di dependency).
     */
    delete: operations["delete_a_calendar_api_v1_calendars_calendars__calendar_id__delete"];
    /**
     * Perbarui Kalender
     * @description Memperbarui detail kalender (nama, warna, visibilitas).
     *
     * Keamanan:
     * Hanya 'owner' atau 'editor' yang dapat memperbarui.
     */
    patch: operations["update_calendar_details_api_v1_calendars_calendars__calendar_id__patch"];
  };
  "/api/v1/calendar_subscriptions/calendars/{calendar_id}/subscriptions/": {
    /** List Anggota (Subscriber) Kalender */
    get: operations["get_subscriptions_for_calendar_api_v1_calendar_subscriptions_calendars__calendar_id__subscriptions__get"];
    /** Undang/Tambah Anggota ke Kalender */
    post: operations["add_subscription_to_calendar_api_v1_calendar_subscriptions_calendars__calendar_id__subscriptions__post"];
  };
  "/api/v1/canvas/": {
    /**
     * List Canvas Pengguna
     * @description Mengambil daftar semua canvas yang dapat diakses oleh pengguna
     * (pribadi, di-share, atau via workspace).
     */
    get: operations["get_my_canvases_api_v1_canvas__get"];
    /**
     * Buat Canvas Baru
     * @description Membuat canvas baru (pribadi atau milik workspace).
     *
     * INPUT: CanvasCreate (title, icon, workspace_id, metadata).
     * OUTPUT: CanvasResponse (Objek canvas yang baru dibuat).
     */
    post: operations["create_new_canvas_api_v1_canvas__post"];
  };
  "/api/v1/canvas/{canvas_id}": {
    /**
     * Get Detail Canvas
     * @description Mengambil detail sebuah canvas.
     * (Endpoint ini bisa dikembangkan untuk A1/A4 Hybrid Snapshot)
     */
    get: operations["get_canvas_details_api_v1_canvas__canvas_id__get"];
    /**
     * Hapus (Arsipkan) Canvas
     * @description Menghapus (mengarsipkan) canvas.
     * Hanya 'owner' atau 'admin' yang dapat melakukan ini.
     *
     * CATATAN: Ini meng-patch 'is_archived=true', bukan DELETE permanen.
     */
    delete: operations["delete_canvas_api_v1_canvas__canvas_id__delete"];
    /**
     * Update Canvas
     * @description Memperbarui detail canvas (judul, ikon, arsip, metadata).
     * Hanya 'owner' atau 'admin' yang dapat melakukan ini.
     */
    patch: operations["update_canvas_details_api_v1_canvas__canvas_id__patch"];
  };
  "/api/v1/canvas/{canvas_id}/blocks": {
    /**
     * List Blocks di Canvas
     * @description Mengambil daftar block di dalam canvas, dengan paginasi.
     */
    get: operations["get_canvas_blocks_api_v1_canvas__canvas_id__blocks_get"];
  };
  "/api/v1/canvas/{canvas_id}/mutate": {
    /**
     * Fallback AJAX Mutate
     * @description Fallback HTTP untuk mutasi (jika WebSocket gagal).
     * Blueprint: H2
     */
    post: operations["http_fallback_mutate_api_v1_canvas__canvas_id__mutate_post"];
  };
  "/api/v1/canvas/{canvas_id}/presence": {
    /**
     * Fallback AJAX Presence
     * @description Fallback HTTP untuk update presence (cursor/typing).
     * Blueprint: H3
     */
    post: operations["http_fallback_presence_api_v1_canvas__canvas_id__presence_post"];
  };
  "/api/v1/canvas/{canvas_id}/leave": {
    /**
     * Manual Leave Presence
     * @description Memberi tahu server bahwa user meninggalkan canvas (HTTP).
     * Blueprint: H6
     */
    post: operations["http_manual_leave_api_v1_canvas__canvas_id__leave_post"];
  };
  "/api/v1/canvas/{canvas_id}/blocks/{block_id}": {
    /**
     * Get Single Block
     * @description Mengambil data satu block spesifik.
     * Blueprint: A3
     */
    get: operations["get_single_block_api_v1_canvas__canvas_id__blocks__block_id__get"];
  };
  "/api/v1/canvas/{canvas_id}/permissions": {
    /**
     * Get Canvas Permissions
     * @description Mendapatkan izin akses user di canvas dan daftar anggota.
     * Blueprint: A8
     */
    get: operations["get_canvas_permissions_api_v1_canvas__canvas_id__permissions_get"];
  };
  "/api/v1/canvas/{canvas_id}/members/": {
    /**
     * List Canvas Members
     * @description Mengambil daftar semua anggota yang memiliki akses langsung
     * ke canvas ini (via tabel CanvasAccess).
     *
     * Keamanan:
     * Hanya pengguna yang sudah memiliki akses (Owner, Member, atau Invited)
     * yang dapat melihat daftar anggota.
     */
    get: operations["get_members_in_canvas_api_v1_canvas__canvas_id__members__get"];
    /**
     * Invite/Add Member to Canvas
     * @description Mengundang (atau menambahkan) pengguna baru ke canvas.
     *
     * Keamanan:
     * Hanya 'owner' dari canvas personal atau 'admin' dari workspace
     * yang dapat mengundang anggota baru.
     *
     * Logika:
     * Saat ini, endpoint ini HANYA mendukung invite via 'user_id'.
     */
    post: operations["invite_member_to_canvas_api_v1_canvas__canvas_id__members__post"];
  };
  "/api/v1/chat/": {
    /**
     * Send chat message (streaming)
     * @description Chat endpoint with frontend-driven model selection.
     *
     * ## Supported Models (by provider):
     *
     * **Gemini (Google)**
     * - `gemini-flash-lite-latest` - Fast, lightweight model
     * - `gemini-2.5-pro` - Advanced reasoning and complex tasks
     * - `gemini-2.5-flash` - Balanced speed and capability
     *
     * **OpenAI**
     * - `gpt-4o-mini` - Fast GPT-4 variant
     * - `gpt-5-pro` - Most advanced model
     * - `gpt-4.1` - Enhanced GPT-4
     *
     * **DeepSeek**
     * - `deepseek-chat` - General conversation
     * - `deepseek-v3` - Latest version
     * - `deepseek-r1` - Reasoning-focused
     *
     * **Kimi (Moonshot)**
     * - `moonshot-v1-32k` - 32K context window
     * - `moonshot-v1-8k` - 8K context window
     * - `moonshot-v1-128k` - 128K context window
     * - `kimi-k2-thinking` - Enhanced reasoning
     *
     * **XAI (Grok)**
     * - `grok-4-fast-reasoning-latest` - Fast reasoning
     * - `grok-4` - Standard model
     * - `grok-code-fast-1` - Code-optimized
     *
     * ## Request Body:
     * - `message`: User's message (required)
     * - `conversation_id`: Conversation UUID (optional, creates new if null)
     * - `llm_config`: Model configuration (optional, uses DEFAULT_MODEL if not provided)
     *     - `model`: Model identifier from list above
     *     - `temperature`: 0.0-2.0 (default: 0.2)
     *     - `max_tokens`: Max output tokens (optional)
     *
     * ## Response:
     * Returns Server-Sent Events (SSE) stream with:
     * - AI response chunks
     * - Token usage metadata
     * - Final state information
     *
     * Use `/models/available` to check which models are currently configured.
     */
    post: operations["handle_chat_api_v1_chat__post"];
  };
  "/api/v1/chat/models/available": {
    /**
     * Get available models
     * @description Get list of LLM models that backend can currently support.
     * Models are only listed if their API keys are configured.
     */
    get: operations["get_available_models_api_v1_chat_models_available_get"];
  };
  "/api/v1/chat/conversations-list": {
    /** List Conversations */
    get: operations["list_conversations_api_v1_chat_conversations_list_get"];
  };
  "/api/v1/chat/{conversation_id}/messages": {
    /** List Messages */
    get: operations["list_messages_api_v1_chat__conversation_id__messages_get"];
  };
  "/api/v1/chat/stream/{conversation_id}/title": {
    /** Stream Judul Percakapan (Real-time) */
    get: operations["stream_conversation_title_api_v1_chat_stream__conversation_id__title_get"];
  };
  "/api/v1/chat/conversations/{conversation_id}": {
    /**
     * Perbarui Judul Percakapan (Manual)
     * @description Endpoint untuk memperbarui judul conversation secara manual.
     */
    patch: operations["update_conversation_title_manual_api_v1_chat_conversations__conversation_id__patch"];
  };
  "/api/v1/chat/{conversation_id}/actions/approve_tool": {
    /**
     * Menyetujui eksekusi tool (Human-in-the-Loop)
     * @description Endpoint ini dipanggil oleh frontend setelah pengguna menekan
     * tombol 'Setuju' pada permintaan persetujuan tool.
     * (Implementasi NFR Poin 11)
     */
    post: operations["approve_tool_execution_api_v1_chat__conversation_id__actions_approve_tool_post"];
  };
  "/api/v1/chat/{conversation_id}/actions/reject_tool": {
    /**
     * Menolak eksekusi tool (Human-in-the-Loop)
     * @description Endpoint ini dipanggil oleh frontend setelah pengguna menekan
     * tombol 'Tolak' pada permintaan persetujuan tool.
     */
    post: operations["reject_tool_execution_api_v1_chat__conversation_id__actions_reject_tool_post"];
  };
  "/api/v1/health": {
    /**
     * Liveness probe
     * @description Simple liveness probe.
     *
     * Returns 200 OK if the application is running.
     * This endpoint doesn't check any dependencies.
     */
    get: operations["liveness_probe_api_v1_health_get"];
  };
  "/api/v1/ready": {
    /**
     * Readiness probe
     * @description Readiness probe.
     *
     * Returns 200 OK if the application and its dependencies are ready.
     * Checks database and Redis connectivity.
     */
    get: operations["readiness_probe_api_v1_ready_get"];
  };
  "/api/v1/debug/echo": {
    /**
     * Echo payload for debugging
     * @description Debug endpoint that echoes back the received payload.
     *
     * This endpoint is useful for testing connectivity and request handling.
     * It's only available in debug mode.
     */
    post: operations["debug_echo_api_v1_debug_echo_post"];
  };
  "/api/v1/metrics": {
    /**
     * Prometheus metrics
     * @description Prometheus metrics endpoint.
     */
    get: operations["metrics_api_v1_metrics_get"];
  };
  "/api/v1/invitations/invitations/workspace/respond": {
    /**
     * Respond to Workspace Invitation
     * @description Endpoint untuk pengguna yang login menerima (accept)
     * atau menolak (reject) undangan workspace.
     *
     * Alur:
     * 1. Pengguna menerima email/notifikasi.
     * 2. Pengguna login ke aplikasi.
     * 3. Frontend mengirim 'token' dan 'action' ke endpoint ini.
     * INPUT: WorkspaceInvitationRespond (token: str, action: InvitationAction ['accept'/'reject']).
     * OUTPUT: Dict[str, Any] (Data anggota baru jika diterima, atau {"status": "rejected"}).
     *
     * KAPAN DIGUNAKAN: Dipanggil oleh klien (setelah pengguna mengklik link di email dan login) untuk memproses token undangan.
     */
    post: operations["respond_to_workspace_invite_api_v1_invitations_invitations_workspace_respond_post"];
  };
  "/api/v1/notifications/notifications/stream": {
    /**
     * Notifications Stream
     * @description Endpoint untuk koneksi Server-Sent Events (SSE).
     * Sekarang menggunakan Redis Pub/Sub untuk skalabilitas.
     */
    get: operations["notifications_stream_api_v1_notifications_notifications_stream_get"];
  };
  "/api/v1/schedules/": {
    /**
     * List Schedules In Workspace
     * @description (Async Native) Mengambil daftar jadwal (legacy) di workspace.
     */
    get: operations["list_schedules_in_workspace_api_v1_schedules__get"];
  };
  "/api/v1/schedules_api/calendars/{calendar_id}/schedules": {
    /**
     * Buat Acara (Schedule) Baru
     * @description Membuat acara (schedule) baru di dalam kalender tertentu.
     *
     * Fitur:
     * - Wajib 'original_timezone' (misal: 'Asia/Jakarta').
     * - Waktu dikonversi dan disimpan sebagai UTC.
     * - Memicu background job untuk ekspansi RRULE (jika ada).
     *
     * KAPAN DIGUNAKAN: Di formulir pembuatan acara Kalender.
     */
    post: operations["create_new_schedule_api_v1_schedules_api_calendars__calendar_id__schedules_post"];
  };
  "/api/v1/schedules_api/schedules/{schedule_id}": {
    /**
     * Get Detail Acara (Schedule)
     * @description Mengambil detail "sumber kebenaran" (source of truth) dari
     * satu acara (schedule).
     *
     * Keamanan:
     * Hanya pengguna yang memiliki akses ke kalender induk
     * (via Owner, Workspace, atau Invite) yang dapat melihat acara ini.
     *
     * KAPAN DIGUNAKAN: Saat pengguna mengklik acara di kalender untuk melihat detail pop-up.
     */
    get: operations["get_schedule_details_api_v1_schedules_api_schedules__schedule_id__get"];
    /**
     * Hapus Acara (Schedule) (Soft Delete)
     * @description Menghapus (Soft Delete) satu acara.
     *
     * Fitur:
     * - Mengatur 'is_deleted = true'.
     * - Memicu background job untuk membersihkan 'ScheduleInstances'.
     *
     * Keamanan:
     * Hanya 'owner' atau 'editor' dari kalender induk.
     */
    delete: operations["delete_a_schedule_api_v1_schedules_api_schedules__schedule_id__delete"];
    /**
     * Update Acara (Schedule)
     * @description Memperbarui detail acara (schedule).
     *
     * Fitur:
     * - Jika 'rrule' atau 'exdate' diubah, background job akan dipicu.
     * - TODO: Menangani 'edit_scope' (this vs all).
     *
     * Keamanan:
     * Hanya 'owner' atau 'editor' dari kalender induk yang dapat
     * memperbarui acara di dalamnya.
     */
    patch: operations["update_schedule_details_api_v1_schedules_api_schedules__schedule_id__patch"];
  };
  "/api/v1/schedule_guests/schedules/{schedule_id}/guests/": {
    /**
     * List Tamu di Acara
     * @description Mengambil daftar semua tamu yang diundang ke acara ini.
     *
     * Keamanan:
     * Hanya pengguna yang sudah memiliki akses (minimal 'viewer')
     * ke kalender induk yang dapat melihat daftar tamu.
     */
    get: operations["list_guests_for_a_schedule_api_v1_schedule_guests_schedules__schedule_id__guests__get"];
    /**
     * Tambah Tamu ke Acara
     * @description Menambahkan tamu (via email atau user_id) ke satu acara.
     *
     * Keamanan:
     * Hanya 'owner' atau 'editor' dari kalender induk yang dapat
     * menambahkan tamu.
     */
    post: operations["add_guest_to_a_schedule_api_v1_schedule_guests_schedules__schedule_id__guests__post"];
  };
  "/api/v1/schedule_guests/schedules/{schedule_id}/guests/respond": {
    /**
     * Respons Undangan (RSVP)
     * @description Endpoint untuk PENGGUNA YANG LOGIN (TAMU) merespons
     * undangan acara (RSVP: accept/decline).
     *
     * Keamanan:
     * Dependency 'GuestAccessDep' memastikan bahwa pengguna yang login
     * adalah tamu yang valid untuk 'schedule_id' ini DAN
     * status undangannya masih 'pending'.
     */
    patch: operations["respond_to_schedule_invite_api_v1_schedule_guests_schedules__schedule_id__guests_respond_patch"];
  };
  "/api/v1/schedule_guests/schedules/{schedule_id}/guests/{guest_id}": {
    /**
     * Hapus/Keluarkan Tamu dari Acara
     * @description Menghapus tamu dari acara.
     *
     * Keamanan:
     * Hanya 'owner' atau 'editor' dari kalender induk yang dapat
     * mengeluarkan tamu.
     */
    delete: operations["remove_guest_from_a_schedule_api_v1_schedule_guests_schedules__schedule_id__guests__guest_id__delete"];
  };
  "/api/v1/views/view/schedules": {
    /**
     * Tampilan Kalender (Cepat)
     * @description Endpoint utama untuk UI Kalender.
     *
     * Fitur:
     * - Sangat cepat: Membaca dari tabel 'ScheduleInstances' (pre-computed).
     * - Terpadu: Mengambil acara dari SEMUA kalender yang di-subscribe pengguna.
     * - Aman: Otomatis mem-filter berdasarkan 'user_id' yang login.
     *
     * KAPAN DIGUNAKAN: Saat memuat tampilan bulan/minggu/hari di UI Kalender. Kunci performa aplikasi.
     */
    get: operations["get_schedule_view_for_user_api_v1_views_view_schedules_get"];
  };
  "/api/v1/views/view/freebusy": {
    /**
     * Cek Ketersediaan (Free/Busy)
     * @description Endpoint skalabel untuk deteksi konflik jadwal.
     *
     * Fitur:
     * - Sangat cepat: Menggunakan 'Redis-first cache'.
     * - Fallback: Jika cache kosong, akan mengambil dari 'ScheduleInstances'
     *   (menggunakan index 'user_id').
     *
     * Mengembalikan:
     * Dict[user_id, List[blok_sibuk]]
     *
     * KAPAN DIGUNAKAN: Saat pengguna mencoba membuat rapat dan perlu mengetahui kapan rekan satu timnya sedang sibuk.
     */
    get: operations["get_freebusy_view_for_users_api_v1_views_view_freebusy_get"];
  };
  "/api/v1/workspaces/": {
    /**
     * List My Workspaces
     * @description Mengambil daftar semua workspace di mana pengguna adalah anggota, dengan pagination.
     *
     * INPUT: Query (page, size).
     * OUTPUT: PaginatedWorkspaceListResponse (items: List[Workspace], total, total_pages).
     *
     * KAPAN DIGUNAKAN: Sidebar navigasi utama atau halaman Dashboard untuk memuat daftar ruang kerja.
     */
    get: operations["list_my_workspaces_api_v1_workspaces__get"];
    /**
     * Create Workspace
     * @description Membuat Workspace baru dan secara otomatis menetapkan pengguna yang sedang login sebagai Owner/Admin.
     *
     * INPUT: WorkspaceCreate (name: str, type: WorkspaceType).
     * OUTPUT: Workspace (ID, owner_user_id, name).
     *
     * KAPAN DIGUNAKAN: Di Dashboard atau modul kreasi Workspace.
     */
    post: operations["create_workspace_api_v1_workspaces__post"];
  };
  "/api/v1/workspaces/{workspace_id}": {
    /**
     * Get Workspace
     * @description **Mengambil detail lengkap satu *workspace* berdasarkan `workspace_id`.**
     *
     * **Keamanan:** Memerlukan **keanggotaan aktif** dalam *workspace* tersebut (diperiksa oleh dependency `WorkspaceMemberDep`).
     */
    get: operations["get_workspace_api_v1_workspaces__workspace_id__get"];
    /**
     * Delete Workspace
     * @description **Menghapus *workspace* secara permanen (Hard Delete).**
     *
     * Semua data terkait (*members*, *canvases*, dll.) akan dihapus.
     *
     * **Keamanan:** Memerlukan peran **Admin**. Penghapusan akan **gagal** jika pengguna
     * bukan *owner* (sesuai logika service).
     */
    delete: operations["delete_workspace_api_v1_workspaces__workspace_id__delete"];
    /**
     * Update Workspace
     * @description **Memperbarui metadata *workspace* (misalnya, nama atau ikon).**
     *
     * Hanya field yang disediakan di *payload* yang akan diperbarui.
     *
     * **Keamanan:** Memerlukan peran **Admin** dalam *workspace* tersebut.
     */
    patch: operations["update_workspace_api_v1_workspaces__workspace_id__patch"];
  };
  "/api/v1/workspace_members/": {
    /**
     * List Workspace Members
     * @description Mengambil daftar semua anggota yang terdaftar di 'WorkspaceMembers'.
     *
     * Keamanan:
     * Hanya anggota yang sudah ada di workspace yang dapat melihat
     * daftar anggota lainnya.
     */
    get: operations["get_members_of_workspace_api_v1_workspace_members__get"];
    /**
     * Invite Member to Workspace
     * @description Mengirim undangan (invite) ke pengguna baru (via Email) atau
     * pengguna yang sudah ada (via User ID).
     *
     * Fitur (Logika "Invite-Only"):
     * Endpoint ini TIDAK menambahkan pengguna secara langsung.
     * Ini membuat entri 'pending' di tabel 'WorkspaceInvitations'.
     * Pengguna yang diundang harus menerima undangan ini.
     *
     * Keamanan:
     * - Hanya 'admin' workspace yang dapat mengirim undangan.
     * - Rate limiting per user (admin): 50 undangan per jam
     * - Rate limiting per workspace: 100 undangan per jam
     * - Rate limiting per email: 5 undangan per jam
     *   (mencegah spam/harassment)
     */
    post: operations["invite_member_to_workspace_api_v1_workspace_members__post"];
  };
  "/api/v1/workspace_members/{user_id_to_update}": {
    /**
     * Update Member Role
     * @description Memperbarui role dari anggota yang SUDAH ADA di 'WorkspaceMembers'.
     *
     * Keamanan:
     * Hanya 'admin' yang bisa mengubah role.
     * Fallback: Mencegah 'owner' diturunkan rolenya.
     */
    patch: operations["update_member_role_api_v1_workspace_members__user_id_to_update__patch"];
  };
  "/api/v1/workspace_members/{user_id_to_remove}": {
    /**
     * Remove Member
     * @description Mengeluarkan (remove) anggota dari 'WorkspaceMembers'.
     *
     * Keamanan:
     * Hanya 'admin' yang bisa mengeluarkan anggota.
     * Fallback: Mencegah 'owner' mengeluarkan dirinya sendiri.
     */
    delete: operations["remove_member_from_workspace_api_v1_workspace_members__user_id_to_remove__delete"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * Block
     * @description Model Pydantic utama untuk data Block (Refleksi Skema DB v0.4.3).
     */
    Block: {
      /**
       * Block Id
       * Format: uuid
       */
      block_id: string;
      /**
       * Canvas Id
       * Format: uuid
       */
      canvas_id: string;
      /** Parent Id */
      parent_id: string | null;
      /** Y Order */
      y_order: string;
      /**
       * Version
       * @default 1
       */
      version?: number;
      /** Created At */
      created_at?: string | null;
      /** Created By */
      created_by?: string | null;
      /** Updated At */
      updated_at?: string | null;
      /** Updated By */
      updated_by?: string | null;
      /** Type */
      type: string;
      /** Content */
      content: string;
      /** Properties */
      properties?: {
        [key: string]: unknown;
      } | null;
      /** Ai Metadata */
      ai_metadata?: {
        [key: string]: unknown;
      } | null;
      /** Vector */
      vector?: unknown;
    };
    /**
     * BlockCreate
     * @description Model Pydantic untuk data yang DIHARAPKAN saat membuat block baru.
     */
    BlockCreate: {
      /** Parent Id */
      parent_id?: string | null;
      type: components["schemas"]["BlockType"];
      /** Content */
      content: string;
      /** Properties */
      properties?: {
        [key: string]: unknown;
      } | null;
      /**
       * Y Order
       * @default a0
       */
      y_order?: string | null;
    };
    /**
     * BlockOperationPayload
     * @description Payload yang dikirim dari klien untuk memicu operasi mutasi
     * pada block (POST /mutate atau WebSocket H1).
     */
    BlockOperationPayload: {
      /**
       * Client Op Id
       * @description UUID unik yang dihasilkan klien untuk idempotency (Tugas 2).
       */
      client_op_id: string;
      /**
       * Block Id
       * @description ID block yang dimutasi. Opsional jika action='create'.
       */
      block_id?: string | null;
      /**
       * Canvas Id
       * Format: uuid
       * @description ID canvas target.
       */
      canvas_id: string;
      /**
       * Update Data
       * @description Data update block (misal: {'content': 'teks baru', 'y_order': 'b1'}).
       */
      update_data: {
        [key: string]: unknown;
      };
      /**
       * Action
       * @description Jenis operasi.
       * @enum {string}
       */
      action: "create" | "update" | "delete";
      /**
       * Expected Version
       * @description Nomor versi block yang diharapkan klien sebelum update/delete (Optimistic Locking).
       */
      expected_version?: number | null;
    };
    /**
     * BlockType
     * @enum {string}
     */
    BlockType: "text" | "task_item" | "heading_1" | "heading_2" | "image" | "code";
    /**
     * BlockUpdate
     * @description Model Pydantic untuk data yang OPSIONAL saat memperbarui block.
     */
    BlockUpdate: {
      /** Content */
      content?: string | null;
      /** Properties */
      properties?: {
        [key: string]: unknown;
      } | null;
      /** Y Order */
      y_order?: string | null;
    };
    /** Body_refresh_access_token_api_v1_auth_refresh_post */
    Body_refresh_access_token_api_v1_auth_refresh_post: {
      /** Refresh Token */
      refresh_token: string;
    };
    /**
     * Calendar
     * @description Model Pydantic untuk Tabel: `Calendars`
     * Mewakili "wadah" atau "folder" kalender.
     */
    Calendar: {
      /**
       * Calendar Id
       * Format: uuid
       */
      calendar_id: string;
      /** Name */
      name: string;
      /** Owner User Id */
      owner_user_id?: string | null;
      /** Workspace Id */
      workspace_id?: string | null;
      visibility: components["schemas"]["CalendarVisibility"];
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      } | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * CalendarCreate
     * @description Payload untuk POST /api/v1/calendars
     */
    CalendarCreate: {
      /** Name */
      name: string;
      /** Workspace Id */
      workspace_id?: string | null;
      /** @default private */
      visibility?: components["schemas"]["CalendarVisibility"] | null;
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * CalendarUpdate
     * @description Payload untuk PATCH /api/v1/calendars/{id}
     */
    CalendarUpdate: {
      /** Name */
      name?: string | null;
      visibility?: components["schemas"]["CalendarVisibility"] | null;
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * CalendarVisibility
     * @description Mengontrol visibilitas default Kalender.
     * (Mencerminkan 'calendar_visibility_enum' di SQL).
     * @enum {string}
     */
    CalendarVisibility: "private" | "workspace" | "public";
    /**
     * CanvasCreate
     * @description Model Pydantic untuk data yang DIHARAPKAN saat membuat canvas baru.
     */
    CanvasCreate: {
      /**
       * Title
       * @description Judul canvas
       */
      title: string;
      /**
       * Icon
       * @description Ikon canvas
       */
      icon?: string | null;
      /**
       * Workspace Id
       * @description ID workspace jika canvas milik workspace
       */
      workspace_id?: string | null;
      /**
       * Canvas Metadata
       * @description Metadata tambahan untuk canvas
       */
      canvas_metadata?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * CanvasListResponse
     * @description Model Pydantic untuk response daftar canvas.
     */
    CanvasListResponse: {
      /**
       * Canvas Id
       * Format: uuid
       */
      canvas_id: string;
      /** Title */
      title: string;
      /** Icon */
      icon?: string | null;
      /** Updated At */
      updated_at?: string | null;
    };
    /**
     * CanvasMemberInvite
     * @description Model Pydantic untuk undangan anggota canvas.
     */
    CanvasMemberInvite: {
      /**
       * Invite Id
       * Format: uuid
       */
      invite_id: string;
      /**
       * Canvas Id
       * Format: uuid
       */
      canvas_id: string;
      /**
       * Inviter User Id
       * Format: uuid
       */
      inviter_user_id: string;
      /** Invitee Email */
      invitee_email: string;
      role: components["schemas"]["CanvasRole"];
      /** Status */
      status: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * CanvasResponse
     * @description Model Pydantic untuk response canvas.
     */
    CanvasResponse: {
      /**
       * Canvas Id
       * Format: uuid
       */
      canvas_id: string;
      /** Workspace Id */
      workspace_id?: string | null;
      /** User Id */
      user_id?: string | null;
      /**
       * Creator User Id
       * Format: uuid
       */
      creator_user_id: string;
      /** Title */
      title: string;
      /** Icon */
      icon?: string | null;
      /**
       * Is Archived
       * @default false
       */
      is_archived?: boolean;
      /** Canvas Metadata */
      canvas_metadata?: {
        [key: string]: unknown;
      } | null;
      /** Created At */
      created_at?: string | null;
      /** Updated At */
      updated_at?: string | null;
      /** Summary Text */
      summary_text?: string | null;
    };
    /**
     * CanvasRole
     * @enum {string}
     */
    CanvasRole: "owner" | "admin" | "editor" | "viewer";
    /**
     * CanvasUpdate
     * @description Model Pydantic untuk data yang OPSIONAL saat memperbarui canvas.
     */
    CanvasUpdate: {
      /**
       * Title
       * @description Judul canvas
       */
      title?: string | null;
      /**
       * Icon
       * @description Ikon canvas
       */
      icon?: string | null;
      /**
       * Is Archived
       * @description Status arsip canvas
       */
      is_archived?: boolean | null;
      /**
       * Canvas Metadata
       * @description Metadata tambahan untuk canvas
       */
      canvas_metadata?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * ChatRequest
     * @example {
     *   "conversation_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
     *   "llm_config": {
     *     "model": "gemini-2.5-flash",
     *     "temperature": 0.7
     *   },
     *   "message": "Explain quantum computing"
     * }
     */
    ChatRequest: {
      /**
       * Message
       * @description User message
       */
      message: string;
      /**
       * Conversation Id
       * @description If null → create new; else reuse if exists
       */
      conversation_id?: string | null;
      /** @description Frontend-selected model/params */
      llm_config?: components["schemas"]["LLMConfig"] | null;
    };
    /**
     * ConversationListItem
     * @description Representasi ringkas dari sebuah conversation untuk list.
     */
    ConversationListItem: {
      /**
       * Conversation Id
       * Format: uuid
       */
      conversation_id: string;
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ConversationTitleUpdate
     * @description Skema payload untuk endpoint PATCH [PATCH /chat/conversations/{id}]
     * yang digunakan untuk memperbarui judul percakapan secara manual.
     */
    ConversationTitleUpdate: {
      /**
       * Title
       * @description Judul baru untuk percakapan.
       */
      title: string;
    };
    /**
     * GuestCreate
     * @description Payload untuk POST /api/v1/schedules/{id}/guests
     * (Mirip dengan logika invite workspace)
     */
    GuestCreate: {
      /**
       * Email
       * @description Email tamu eksternal.
       */
      email?: string | null;
      /**
       * User Id
       * @description User ID tamu internal.
       */
      user_id?: string | null;
      /** @default guest */
      role?: components["schemas"]["GuestRole"] | null;
    };
    /**
     * GuestRole
     * @description Mengontrol hak akses Tamu di dalam satu Acara.
     * (Mencerminkan 'guest_role_enum' di SQL).
     * @enum {string}
     */
    GuestRole: "guest" | "co-host";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * InvitationAction
     * @description Mendefinisikan tindakan yang valid untuk merespons undangan.
     * @enum {string}
     */
    InvitationAction: "accept" | "reject";
    /**
     * LLMConfig
     * @description LLM configuration per request.
     */
    LLMConfig: {
      /**
       * Model
       * @description Model identifier (e.g., 'gemini-2.5-flash')
       */
      model: string;
      /**
       * Temperature
       * @description 0.0-2.0
       * @default 0.2
       */
      temperature?: number | null;
      /**
       * Max Tokens
       * @description Optional max tokens
       */
      max_tokens?: number | null;
    };
    /**
     * MemberRole
     * @description Mendefinisikan role anggota yang valid di 'WorkspaceMembers'.
     * @enum {string}
     */
    MemberRole: "admin" | "member" | "guest";
    /**
     * MessageListItem
     * @description Representasi ringkas dari satu pesan (user atau assistant).
     */
    MessageListItem: {
      /**
       * Message Id
       * Format: uuid
       */
      message_id: string;
      /**
       * Role
       * @enum {string}
       */
      role: "user" | "assistant" | "system" | "tool";
      /** Content */
      content: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * PaginatedConversationListResponse
     * @description Response model untuk endpoint list conversation dengan pagination.
     */
    PaginatedConversationListResponse: {
      /** Items */
      items: components["schemas"]["ConversationListItem"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Size */
      size: number;
      /** Total Pages */
      total_pages: number;
    };
    /**
     * PaginatedMessageListResponse
     * @description Response model untuk endpoint list pesan dalam satu conversation.
     */
    PaginatedMessageListResponse: {
      /** Items */
      items: components["schemas"]["MessageListItem"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Size */
      size: number;
      /** Total Pages */
      total_pages: number;
    };
    /** PaginatedScheduleInstanceResponse */
    PaginatedScheduleInstanceResponse: {
      /** Items */
      items: components["schemas"]["ScheduleInstance"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Size */
      size: number;
      /** Total Pages */
      total_pages: number;
    };
    /**
     * PaginatedWorkspaceListResponse
     * @description Skema Pydantic untuk MENGEMBALIKAN daftar workspace yang dipaginasi.
     */
    PaginatedWorkspaceListResponse: {
      /** Items */
      items: components["schemas"]["Workspace"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Size */
      size: number;
      /** Total Pages */
      total_pages: number;
    };
    /**
     * RsvpStatus
     * @description Status respons RSVP dari seorang Tamu.
     * (Mencerminkan 'rsvp_status_enum' di SQL).
     * @enum {string}
     */
    RsvpStatus: "pending" | "accepted" | "declined";
    /**
     * Schedule
     * @description Model Pydantic untuk Tabel: `Schedules`
     * Mewakili "sumber kebenaran" (source of truth) dari sebuah acara.
     */
    Schedule: {
      /**
       * Schedule Id
       * Format: uuid
       */
      schedule_id: string;
      /**
       * Calendar Id
       * Format: uuid
       */
      calendar_id: string;
      /** Title */
      title: string;
      /**
       * Start Time
       * Format: date-time
       */
      start_time: string;
      /**
       * End Time
       * Format: date-time
       */
      end_time: string;
      /** Schedule Metadata */
      schedule_metadata?: {
        [key: string]: unknown;
      } | null;
      /** Rrule */
      rrule?: string | null;
      /** Rdate */
      rdate?: string[] | null;
      /** Exdate */
      exdate?: string[] | null;
      /** Parent Schedule Id */
      parent_schedule_id?: string | null;
      /**
       * Creator User Id
       * Format: uuid
       */
      creator_user_id: string;
      /** Is Deleted */
      is_deleted: boolean;
      /** Deleted At */
      deleted_at?: string | null;
      /** Version */
      version: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ScheduleCreate
     * @description Payload untuk POST /api/v1/calendars/{id}/schedules
     */
    ScheduleCreate: {
      /** Title */
      title: string;
      /**
       * Start Time
       * Format: date-time
       */
      start_time: string;
      /**
       * End Time
       * Format: date-time
       */
      end_time: string;
      /**
       * Original Timezone
       * @description IANA Timezone (misal: 'Asia/Jakarta'). Wajib untuk konversi UTC.
       */
      original_timezone: string;
      /** Rrule */
      rrule?: string | null;
      /** Rdate */
      rdate?: string[] | null;
      /** Exdate */
      exdate?: string[] | null;
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * ScheduleGuest
     * @description Model Pydantic untuk Tabel: `ScheduleGuests`
     * Mewakili tamu yang diundang ke satu acara.
     */
    ScheduleGuest: {
      /**
       * Guest Id
       * Format: uuid
       */
      guest_id: string;
      /**
       * Schedule Id
       * Format: uuid
       */
      schedule_id: string;
      /** User Id */
      user_id?: string | null;
      /** Guest Email */
      guest_email?: string | null;
      response_status: components["schemas"]["RsvpStatus"];
      role: components["schemas"]["GuestRole"];
    };
    /**
     * ScheduleInstance
     * @description Model Pydantic untuk Tabel: `ScheduleInstances`
     * Mewakili acara yang sudah di-ekspansi (pre-computed).
     * Ini adalah KUNCI PERFORMA.
     */
    ScheduleInstance: {
      /**
       * Instance Id
       * Format: uuid
       */
      instance_id: string;
      /**
       * Schedule Id
       * Format: uuid
       */
      schedule_id: string;
      /**
       * Calendar Id
       * Format: uuid
       */
      calendar_id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /**
       * Start Time
       * Format: date-time
       */
      start_time: string;
      /**
       * End Time
       * Format: date-time
       */
      end_time: string;
      /** Is Exception */
      is_exception: boolean;
      /** Is Deleted */
      is_deleted: boolean;
    };
    /**
     * ScheduleUpdate
     * @description Payload untuk PATCH /api/v1/schedules/{id}
     */
    ScheduleUpdate: {
      /** Title */
      title?: string | null;
      /** Start Time */
      start_time?: string | null;
      /** End Time */
      end_time?: string | null;
      /** Original Timezone */
      original_timezone?: string | null;
      /** Rrule */
      rrule?: string | null;
      /** Rdate */
      rdate?: string[] | null;
      /** Exdate */
      exdate?: string[] | null;
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      } | null;
      /**
       * Edit Scope
       * @description Tentukan cara mengedit acara berulang
       */
      edit_scope?: ("this" | "this_and_following") | null;
    };
    /**
     * SubscriptionCreate
     * @description Payload untuk POST /api/v1/calendars/{id}/subscriptions (Undang orang)
     */
    SubscriptionCreate: {
      /**
       * User Id
       * Format: uuid
       * @description User ID yang akan diundang.
       */
      user_id: string;
      /**
       * @description Role yang diberikan.
       * @default viewer
       */
      role?: components["schemas"]["SubscriptionRole"];
    };
    /**
     * SubscriptionRole
     * @description Mengontrol hak akses Pengguna ke Kalender.
     * (Mencerminkan 'calendar_subscription_role_enum' di SQL).
     * @enum {string}
     */
    SubscriptionRole: "owner" | "editor" | "viewer";
    /**
     * SubscriptionTier
     * @enum {string}
     */
    SubscriptionTier: "user" | "pro" | "admin";
    /** User */
    User: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Name */
      name?: string | null;
      subscription_tier: components["schemas"]["SubscriptionTier"];
    };
    /**
     * UserMetadataUpdate
     * @description Skema untuk data di dalam 'user_metadata' (JSONB).
     * Fokus pada 'no hp' (phone_number).
     */
    UserMetadataUpdate: {
      /**
       * Phone Number
       * @description Nomor telepon pengguna.
       */
      phone_number?: string | null;
    };
    /**
     * UserUpdate
     * @description Skema payload untuk endpoint [PATCH /auth/me].
     * Semua field bersifat opsional untuk 'PATCH'.
     */
    UserUpdate: {
      /**
       * Name
       * @description Nama lengkap baru pengguna.
       */
      name?: string | null;
      /**
       * Email
       * @description Alamat email baru pengguna.
       */
      email?: string | null;
      /** @description Metadata baru pengguna. */
      metadata?: components["schemas"]["UserMetadataUpdate"] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * Workspace
     * @description Skema Pydantic untuk MEREPRESENTASIKAN data workspace dari database.
     */
    Workspace: {
      /**
       * Workspace Id
       * Format: uuid
       */
      workspace_id: string;
      /**
       * Owner User Id
       * Format: uuid
       */
      owner_user_id: string;
      /** Name */
      name: string;
      type: components["schemas"]["WorkspaceType"];
      /** Workspace Metadata */
      workspace_metadata?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * WorkspaceCreate
     * @description Skema Pydantic untuk validasi payload saat MEMBUAT workspace.
     */
    WorkspaceCreate: {
      /** Name */
      name: string;
      /** @default personal */
      type?: components["schemas"]["WorkspaceType"];
    };
    /**
     * WorkspaceInvitationRespond
     * @description Skema payload untuk POST /invitations/workspace/respond.
     * Digunakan oleh pengguna yang login untuk menerima/menolak undangan.
     */
    WorkspaceInvitationRespond: {
      /**
       * Token
       * @description Token undangan unik yang diterima (misal: dari email).
       */
      token: string;
      /** @description Tindakan yang diambil (accept atau reject). */
      action: components["schemas"]["InvitationAction"];
    };
    /**
     * WorkspaceMemberDetails
     * @description Skema Pydantic untuk data pengguna (sub-set dari User model).
     * Digunakan dalam 'WorkspaceMemberResponse' untuk keamanan.
     */
    WorkspaceMemberDetails: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Name */
      name?: string | null;
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /**
     * WorkspaceMemberInviteOrAdd
     * @description Skema payload untuk POST /workspaces/{id}/members.
     *
     * Fitur:
     * Model ini fleksibel, memungkinkan frontend mengirim:
     * 1. 'user_id' (untuk mengundang pengguna yang sudah ada).
     * 2. 'email' (untuk mengundang pengguna eksternal).
     *
     * Validator di bawah memastikan hanya salah satu yang disediakan.
     */
    WorkspaceMemberInviteOrAdd: {
      /**
       * Email
       * @description Email pengguna yang akan diundang (jika pengguna eksternal).
       */
      email?: string | null;
      /**
       * User Id
       * @description User ID pengguna yang akan ditambahkan (jika pengguna sudah ada).
       */
      user_id?: string | null;
      /**
       * @description Role yang akan diberikan.
       * @default member
       */
      role?: components["schemas"]["MemberRole"];
    };
    /**
     * WorkspaceMemberResponse
     * @description Skema respons untuk GET /workspaces/{id}/members.
     * Menggabungkan 'role' anggota dengan detail 'user'.
     */
    WorkspaceMemberResponse: {
      role: components["schemas"]["MemberRole"];
      user: components["schemas"]["WorkspaceMemberDetails"];
    };
    /**
     * WorkspaceMemberUpdate
     * @description Skema payload untuk PATCH /workspaces/{id}/members/{user_id}.
     * Hanya mengizinkan perubahan 'role'.
     */
    WorkspaceMemberUpdate: {
      /** @description Role baru untuk anggota workspace. */
      role: components["schemas"]["MemberRole"];
    };
    /**
     * WorkspaceType
     * @description Mendefinisikan tipe workspace (personal vs tim).
     * @enum {string}
     */
    WorkspaceType: "personal" | "team";
    /**
     * WorkspaceUpdate
     * @description Skema Pydantic untuk validasi payload saat MEMPERBARUI workspace.
     */
    WorkspaceUpdate: {
      /** Name */
      name: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Read Users Me
   * @description Mengambil data profil lengkap (User model) untuk pengguna yang saat ini terotentikasi.
   *
   * INPUT: None (Otentikasi melalui header JWT).
   * OUTPUT: User (ID, email, nama, subscription_tier).
   *
   * KAPAN DIGUNAKAN: Dipanggil saat inisialisasi aplikasi atau setelah login/refresh sesi untuk memverifikasi keaktifan sesi dan memuat detail pengguna ke UI.
   */
  read_users_me_api_v1_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  /**
   * Update Users Me
   * @description Memperbarui atribut tertentu dari profil pengguna yang sedang login (nama, email, metadata).
   *
   * INPUT: UserUpdate (Opsional: name, email, metadata: {phone_number: str}).
   * OUTPUT: User (Objek pengguna yang telah diperbarui).
   *
   * KAPAN DIGUNAKAN: Di halaman 'Settings' pengguna saat memperbarui informasi profil. Memerlukan sinkronisasi antara tabel 'auth.users' dan 'public.Users'.
   */
  update_users_me_api_v1_auth_me_patch: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Refresh JWT access token
   * @description Refresh JWT access token using a valid refresh token.
   *
   * This endpoint exchanges a valid refresh token for a new JWT access token.
   * The refresh token must be valid and not expired.
   */
  refresh_access_token_api_v1_auth_refresh_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_refresh_access_token_api_v1_auth_refresh_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Blocks In Canvas Endpoint
   * @description Endpoint untuk mengambil semua block dalam sebuah canvas.
   */
  list_blocks_in_canvas_endpoint_api_v1_blocks__get: {
    parameters: {
      query: {
        canvas_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Block"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create New Block Endpoint
   * @description Endpoint untuk membuat block baru. Meneruskan user_id (created_by) untuk audit.
   */
  create_new_block_endpoint_api_v1_blocks__post: {
    parameters: {
      query: {
        canvas_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BlockCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["Block"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete A Block Endpoint
   * @description Endpoint untuk menghapus block beserta embeddingnya.
   */
  delete_a_block_endpoint_api_v1_blocks__block_id__delete: {
    parameters: {
      query: {
        canvas_id: string;
      };
      path: {
        block_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Block Content Endpoint
   * @description Endpoint untuk memperbarui block. Meneruskan user_id (updated_by) untuk audit.
   */
  update_block_content_endpoint_api_v1_blocks__block_id__patch: {
    parameters: {
      query: {
        canvas_id: string;
      };
      path: {
        block_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BlockUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Block"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Kalender Saya (yang di-subscribe)
   * @description Mengambil daftar semua kalender yang di-subscribe oleh pengguna.
   *
   * Fitur:
   * Ini mengembalikan 'role' pengguna di kalender tersebut
   * beserta detail kalendernya (JOIN).
   */
  get_my_subscribed_calendars_api_v1_calendars_calendars__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
              [key: string]: unknown;
            }[];
        };
      };
    };
  };
  /**
   * Buat Kalender Baru
   * @description Membuat "wadah" kalender baru. Pembuat otomatis ditambahkan sebagai 'owner'
   *
   * Fitur:
   * - Jika 'workspace_id' disediakan, kalender ini milik workspace.
   * - Jika tidak, kalender ini bersifat pribadi ('owner_user_id' diisi otomatis).
   * - Pembuat otomatis ditambahkan sebagai 'owner' di 'CalendarSubscriptions'.
   *
   * INPUT: CalendarCreate (name: str, workspace_id: Optional[UUID]).
   * OUTPUT: Calendar (ID, name, owner/workspace ID).
   *
   * KAPAN DIGUNAKAN: Di UI Kalender saat pengguna membuat kalender baru.
   */
  create_new_calendar_api_v1_calendars_calendars__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CalendarCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["Calendar"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Hapus Kalender
   * @description Menghapus kalender secara permanen.
   *
   * Fitur:
   * Semua 'Subscriptions', 'Schedules', dan 'Instances' terkait
   * akan dihapus oleh 'ON DELETE CASCADE' di database.
   *
   * Keamanan:
   * Hanya 'owner' atau 'editor' (sesuai 'get_calendar_editor_access').
   * (Kita mungkin perlu memperketat ini HANYA untuk 'owner' di dependency).
   */
  delete_a_calendar_api_v1_calendars_calendars__calendar_id__delete: {
    parameters: {
      path: {
        calendar_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Perbarui Kalender
   * @description Memperbarui detail kalender (nama, warna, visibilitas).
   *
   * Keamanan:
   * Hanya 'owner' atau 'editor' yang dapat memperbarui.
   */
  update_calendar_details_api_v1_calendars_calendars__calendar_id__patch: {
    parameters: {
      path: {
        calendar_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CalendarUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Calendar"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Anggota (Subscriber) Kalender */
  get_subscriptions_for_calendar_api_v1_calendar_subscriptions_calendars__calendar_id__subscriptions__get: {
    parameters: {
      path: {
        calendar_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
              [key: string]: unknown;
            }[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Undang/Tambah Anggota ke Kalender */
  add_subscription_to_calendar_api_v1_calendar_subscriptions_calendars__calendar_id__subscriptions__post: {
    parameters: {
      path: {
        calendar_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubscriptionCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Canvas Pengguna
   * @description Mengambil daftar semua canvas yang dapat diakses oleh pengguna
   * (pribadi, di-share, atau via workspace).
   */
  get_my_canvases_api_v1_canvas__get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CanvasListResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Buat Canvas Baru
   * @description Membuat canvas baru (pribadi atau milik workspace).
   *
   * INPUT: CanvasCreate (title, icon, workspace_id, metadata).
   * OUTPUT: CanvasResponse (Objek canvas yang baru dibuat).
   */
  create_new_canvas_api_v1_canvas__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CanvasCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["CanvasResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Detail Canvas
   * @description Mengambil detail sebuah canvas.
   * (Endpoint ini bisa dikembangkan untuk A1/A4 Hybrid Snapshot)
   */
  get_canvas_details_api_v1_canvas__canvas_id__get: {
    parameters: {
      path: {
        canvas_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CanvasResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Hapus (Arsipkan) Canvas
   * @description Menghapus (mengarsipkan) canvas.
   * Hanya 'owner' atau 'admin' yang dapat melakukan ini.
   *
   * CATATAN: Ini meng-patch 'is_archived=true', bukan DELETE permanen.
   */
  delete_canvas_api_v1_canvas__canvas_id__delete: {
    parameters: {
      path: {
        canvas_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Canvas
   * @description Memperbarui detail canvas (judul, ikon, arsip, metadata).
   * Hanya 'owner' atau 'admin' yang dapat melakukan ini.
   */
  update_canvas_details_api_v1_canvas__canvas_id__patch: {
    parameters: {
      path: {
        canvas_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CanvasUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CanvasResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Blocks di Canvas
   * @description Mengambil daftar block di dalam canvas, dengan paginasi.
   */
  get_canvas_blocks_api_v1_canvas__canvas_id__blocks_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      path: {
        canvas_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Block"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Fallback AJAX Mutate
   * @description Fallback HTTP untuk mutasi (jika WebSocket gagal).
   * Blueprint: H2
   */
  http_fallback_mutate_api_v1_canvas__canvas_id__mutate_post: {
    parameters: {
      path: {
        canvas_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BlockOperationPayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Fallback AJAX Presence
   * @description Fallback HTTP untuk update presence (cursor/typing).
   * Blueprint: H3
   */
  http_fallback_presence_api_v1_canvas__canvas_id__presence_post: {
    parameters: {
      path: {
        canvas_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Manual Leave Presence
   * @description Memberi tahu server bahwa user meninggalkan canvas (HTTP).
   * Blueprint: H6
   */
  http_manual_leave_api_v1_canvas__canvas_id__leave_post: {
    parameters: {
      path: {
        canvas_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Single Block
   * @description Mengambil data satu block spesifik.
   * Blueprint: A3
   */
  get_single_block_api_v1_canvas__canvas_id__blocks__block_id__get: {
    parameters: {
      path: {
        block_id: string;
        canvas_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Block"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Canvas Permissions
   * @description Mendapatkan izin akses user di canvas dan daftar anggota.
   * Blueprint: A8
   */
  get_canvas_permissions_api_v1_canvas__canvas_id__permissions_get: {
    parameters: {
      path: {
        canvas_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Canvas Members
   * @description Mengambil daftar semua anggota yang memiliki akses langsung
   * ke canvas ini (via tabel CanvasAccess).
   *
   * Keamanan:
   * Hanya pengguna yang sudah memiliki akses (Owner, Member, atau Invited)
   * yang dapat melihat daftar anggota.
   */
  get_members_in_canvas_api_v1_canvas__canvas_id__members__get: {
    parameters: {
      path: {
        canvas_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
              [key: string]: unknown;
            }[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Invite/Add Member to Canvas
   * @description Mengundang (atau menambahkan) pengguna baru ke canvas.
   *
   * Keamanan:
   * Hanya 'owner' dari canvas personal atau 'admin' dari workspace
   * yang dapat mengundang anggota baru.
   *
   * Logika:
   * Saat ini, endpoint ini HANYA mendukung invite via 'user_id'.
   */
  invite_member_to_canvas_api_v1_canvas__canvas_id__members__post: {
    parameters: {
      path: {
        canvas_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CanvasMemberInvite"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Send chat message (streaming)
   * @description Chat endpoint with frontend-driven model selection.
   *
   * ## Supported Models (by provider):
   *
   * **Gemini (Google)**
   * - `gemini-flash-lite-latest` - Fast, lightweight model
   * - `gemini-2.5-pro` - Advanced reasoning and complex tasks
   * - `gemini-2.5-flash` - Balanced speed and capability
   *
   * **OpenAI**
   * - `gpt-4o-mini` - Fast GPT-4 variant
   * - `gpt-5-pro` - Most advanced model
   * - `gpt-4.1` - Enhanced GPT-4
   *
   * **DeepSeek**
   * - `deepseek-chat` - General conversation
   * - `deepseek-v3` - Latest version
   * - `deepseek-r1` - Reasoning-focused
   *
   * **Kimi (Moonshot)**
   * - `moonshot-v1-32k` - 32K context window
   * - `moonshot-v1-8k` - 8K context window
   * - `moonshot-v1-128k` - 128K context window
   * - `kimi-k2-thinking` - Enhanced reasoning
   *
   * **XAI (Grok)**
   * - `grok-4-fast-reasoning-latest` - Fast reasoning
   * - `grok-4` - Standard model
   * - `grok-code-fast-1` - Code-optimized
   *
   * ## Request Body:
   * - `message`: User's message (required)
   * - `conversation_id`: Conversation UUID (optional, creates new if null)
   * - `llm_config`: Model configuration (optional, uses DEFAULT_MODEL if not provided)
   *     - `model`: Model identifier from list above
   *     - `temperature`: 0.0-2.0 (default: 0.2)
   *     - `max_tokens`: Max output tokens (optional)
   *
   * ## Response:
   * Returns Server-Sent Events (SSE) stream with:
   * - AI response chunks
   * - Token usage metadata
   * - Final state information
   *
   * Use `/models/available` to check which models are currently configured.
   */
  handle_chat_api_v1_chat__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get available models
   * @description Get list of LLM models that backend can currently support.
   * Models are only listed if their API keys are configured.
   */
  get_available_models_api_v1_chat_models_available_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** List Conversations */
  list_conversations_api_v1_chat_conversations_list_get: {
    parameters: {
      query?: {
        /** @description Nomor halaman, dimulai dari 1 */
        page?: number;
        /** @description Jumlah item per halaman (maks 100) */
        size?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedConversationListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Messages */
  list_messages_api_v1_chat__conversation_id__messages_get: {
    parameters: {
      query?: {
        /** @description Nomor halaman, dimulai dari 1 */
        page?: number;
        /** @description Jumlah item per halaman (maks 100) */
        size?: number;
      };
      path: {
        conversation_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedMessageListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Stream Judul Percakapan (Real-time) */
  stream_conversation_title_api_v1_chat_stream__conversation_id__title_get: {
    parameters: {
      path: {
        conversation_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Perbarui Judul Percakapan (Manual)
   * @description Endpoint untuk memperbarui judul conversation secara manual.
   */
  update_conversation_title_manual_api_v1_chat_conversations__conversation_id__patch: {
    parameters: {
      path: {
        conversation_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConversationTitleUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ConversationListItem"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Menyetujui eksekusi tool (Human-in-the-Loop)
   * @description Endpoint ini dipanggil oleh frontend setelah pengguna menekan
   * tombol 'Setuju' pada permintaan persetujuan tool.
   * (Implementasi NFR Poin 11)
   */
  approve_tool_execution_api_v1_chat__conversation_id__actions_approve_tool_post: {
    parameters: {
      path: {
        conversation_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Menolak eksekusi tool (Human-in-the-Loop)
   * @description Endpoint ini dipanggil oleh frontend setelah pengguna menekan
   * tombol 'Tolak' pada permintaan persetujuan tool.
   */
  reject_tool_execution_api_v1_chat__conversation_id__actions_reject_tool_post: {
    parameters: {
      path: {
        conversation_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Liveness probe
   * @description Simple liveness probe.
   *
   * Returns 200 OK if the application is running.
   * This endpoint doesn't check any dependencies.
   */
  liveness_probe_api_v1_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Readiness probe
   * @description Readiness probe.
   *
   * Returns 200 OK if the application and its dependencies are ready.
   * Checks database and Redis connectivity.
   */
  readiness_probe_api_v1_ready_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Echo payload for debugging
   * @description Debug endpoint that echoes back the received payload.
   *
   * This endpoint is useful for testing connectivity and request handling.
   * It's only available in debug mode.
   */
  debug_echo_api_v1_debug_echo_post: {
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Prometheus metrics
   * @description Prometheus metrics endpoint.
   */
  metrics_api_v1_metrics_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Respond to Workspace Invitation
   * @description Endpoint untuk pengguna yang login menerima (accept)
   * atau menolak (reject) undangan workspace.
   *
   * Alur:
   * 1. Pengguna menerima email/notifikasi.
   * 2. Pengguna login ke aplikasi.
   * 3. Frontend mengirim 'token' dan 'action' ke endpoint ini.
   * INPUT: WorkspaceInvitationRespond (token: str, action: InvitationAction ['accept'/'reject']).
   * OUTPUT: Dict[str, Any] (Data anggota baru jika diterima, atau {"status": "rejected"}).
   *
   * KAPAN DIGUNAKAN: Dipanggil oleh klien (setelah pengguna mengklik link di email dan login) untuk memproses token undangan.
   */
  respond_to_workspace_invite_api_v1_invitations_invitations_workspace_respond_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkspaceInvitationRespond"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Notifications Stream
   * @description Endpoint untuk koneksi Server-Sent Events (SSE).
   * Sekarang menggunakan Redis Pub/Sub untuk skalabilitas.
   */
  notifications_stream_api_v1_notifications_notifications_stream_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * List Schedules In Workspace
   * @description (Async Native) Mengambil daftar jadwal (legacy) di workspace.
   */
  list_schedules_in_workspace_api_v1_schedules__get: {
    parameters: {
      query: {
        workspace_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Schedule"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Buat Acara (Schedule) Baru
   * @description Membuat acara (schedule) baru di dalam kalender tertentu.
   *
   * Fitur:
   * - Wajib 'original_timezone' (misal: 'Asia/Jakarta').
   * - Waktu dikonversi dan disimpan sebagai UTC.
   * - Memicu background job untuk ekspansi RRULE (jika ada).
   *
   * KAPAN DIGUNAKAN: Di formulir pembuatan acara Kalender.
   */
  create_new_schedule_api_v1_schedules_api_calendars__calendar_id__schedules_post: {
    parameters: {
      path: {
        calendar_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScheduleCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["Schedule"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Detail Acara (Schedule)
   * @description Mengambil detail "sumber kebenaran" (source of truth) dari
   * satu acara (schedule).
   *
   * Keamanan:
   * Hanya pengguna yang memiliki akses ke kalender induk
   * (via Owner, Workspace, atau Invite) yang dapat melihat acara ini.
   *
   * KAPAN DIGUNAKAN: Saat pengguna mengklik acara di kalender untuk melihat detail pop-up.
   */
  get_schedule_details_api_v1_schedules_api_schedules__schedule_id__get: {
    parameters: {
      path: {
        schedule_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Schedule"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Hapus Acara (Schedule) (Soft Delete)
   * @description Menghapus (Soft Delete) satu acara.
   *
   * Fitur:
   * - Mengatur 'is_deleted = true'.
   * - Memicu background job untuk membersihkan 'ScheduleInstances'.
   *
   * Keamanan:
   * Hanya 'owner' atau 'editor' dari kalender induk.
   */
  delete_a_schedule_api_v1_schedules_api_schedules__schedule_id__delete: {
    parameters: {
      path: {
        schedule_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Acara (Schedule)
   * @description Memperbarui detail acara (schedule).
   *
   * Fitur:
   * - Jika 'rrule' atau 'exdate' diubah, background job akan dipicu.
   * - TODO: Menangani 'edit_scope' (this vs all).
   *
   * Keamanan:
   * Hanya 'owner' atau 'editor' dari kalender induk yang dapat
   * memperbarui acara di dalamnya.
   */
  update_schedule_details_api_v1_schedules_api_schedules__schedule_id__patch: {
    parameters: {
      path: {
        schedule_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScheduleUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Schedule"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Tamu di Acara
   * @description Mengambil daftar semua tamu yang diundang ke acara ini.
   *
   * Keamanan:
   * Hanya pengguna yang sudah memiliki akses (minimal 'viewer')
   * ke kalender induk yang dapat melihat daftar tamu.
   */
  list_guests_for_a_schedule_api_v1_schedule_guests_schedules__schedule_id__guests__get: {
    parameters: {
      path: {
        schedule_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ScheduleGuest"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Tambah Tamu ke Acara
   * @description Menambahkan tamu (via email atau user_id) ke satu acara.
   *
   * Keamanan:
   * Hanya 'owner' atau 'editor' dari kalender induk yang dapat
   * menambahkan tamu.
   */
  add_guest_to_a_schedule_api_v1_schedule_guests_schedules__schedule_id__guests__post: {
    parameters: {
      path: {
        schedule_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GuestCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ScheduleGuest"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Respons Undangan (RSVP)
   * @description Endpoint untuk PENGGUNA YANG LOGIN (TAMU) merespons
   * undangan acara (RSVP: accept/decline).
   *
   * Keamanan:
   * Dependency 'GuestAccessDep' memastikan bahwa pengguna yang login
   * adalah tamu yang valid untuk 'schedule_id' ini DAN
   * status undangannya masih 'pending'.
   */
  respond_to_schedule_invite_api_v1_schedule_guests_schedules__schedule_id__guests_respond_patch: {
    parameters: {
      query: {
        action: components["schemas"]["RsvpStatus"];
      };
      path: {
        schedule_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ScheduleGuest"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Hapus/Keluarkan Tamu dari Acara
   * @description Menghapus tamu dari acara.
   *
   * Keamanan:
   * Hanya 'owner' atau 'editor' dari kalender induk yang dapat
   * mengeluarkan tamu.
   */
  remove_guest_from_a_schedule_api_v1_schedule_guests_schedules__schedule_id__guests__guest_id__delete: {
    parameters: {
      path: {
        schedule_id: string;
        guest_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Tampilan Kalender (Cepat)
   * @description Endpoint utama untuk UI Kalender.
   *
   * Fitur:
   * - Sangat cepat: Membaca dari tabel 'ScheduleInstances' (pre-computed).
   * - Terpadu: Mengambil acara dari SEMUA kalender yang di-subscribe pengguna.
   * - Aman: Otomatis mem-filter berdasarkan 'user_id' yang login.
   *
   * KAPAN DIGUNAKAN: Saat memuat tampilan bulan/minggu/hari di UI Kalender. Kunci performa aplikasi.
   */
  get_schedule_view_for_user_api_v1_views_view_schedules_get: {
    parameters: {
      query: {
        start: string;
        end: string;
        page?: number;
        size?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedScheduleInstanceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Cek Ketersediaan (Free/Busy)
   * @description Endpoint skalabel untuk deteksi konflik jadwal.
   *
   * Fitur:
   * - Sangat cepat: Menggunakan 'Redis-first cache'.
   * - Fallback: Jika cache kosong, akan mengambil dari 'ScheduleInstances'
   *   (menggunakan index 'user_id').
   *
   * Mengembalikan:
   * Dict[user_id, List[blok_sibuk]]
   *
   * KAPAN DIGUNAKAN: Saat pengguna mencoba membuat rapat dan perlu mengetahui kapan rekan satu timnya sedang sibuk.
   */
  get_freebusy_view_for_users_api_v1_views_view_freebusy_get: {
    parameters: {
      query: {
        /** @description Waktu mulai (UTC) */
        start: string;
        /** @description Waktu selesai (UTC) */
        end: string;
        /** @description Daftar User ID yang ingin dicek. */
        user_ids: string[];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: {
                [key: string]: unknown;
              }[];
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List My Workspaces
   * @description Mengambil daftar semua workspace di mana pengguna adalah anggota, dengan pagination.
   *
   * INPUT: Query (page, size).
   * OUTPUT: PaginatedWorkspaceListResponse (items: List[Workspace], total, total_pages).
   *
   * KAPAN DIGUNAKAN: Sidebar navigasi utama atau halaman Dashboard untuk memuat daftar ruang kerja.
   */
  list_my_workspaces_api_v1_workspaces__get: {
    parameters: {
      query?: {
        /** @description Nomor halaman, dimulai dari 1 */
        page?: number;
        /** @description Jumlah item per halaman (maks 100) */
        size?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedWorkspaceListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Workspace
   * @description Membuat Workspace baru dan secara otomatis menetapkan pengguna yang sedang login sebagai Owner/Admin.
   *
   * INPUT: WorkspaceCreate (name: str, type: WorkspaceType).
   * OUTPUT: Workspace (ID, owner_user_id, name).
   *
   * KAPAN DIGUNAKAN: Di Dashboard atau modul kreasi Workspace.
   */
  create_workspace_api_v1_workspaces__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkspaceCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["Workspace"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Workspace
   * @description **Mengambil detail lengkap satu *workspace* berdasarkan `workspace_id`.**
   *
   * **Keamanan:** Memerlukan **keanggotaan aktif** dalam *workspace* tersebut (diperiksa oleh dependency `WorkspaceMemberDep`).
   */
  get_workspace_api_v1_workspaces__workspace_id__get: {
    parameters: {
      path: {
        workspace_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Workspace"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Workspace
   * @description **Menghapus *workspace* secara permanen (Hard Delete).**
   *
   * Semua data terkait (*members*, *canvases*, dll.) akan dihapus.
   *
   * **Keamanan:** Memerlukan peran **Admin**. Penghapusan akan **gagal** jika pengguna
   * bukan *owner* (sesuai logika service).
   */
  delete_workspace_api_v1_workspaces__workspace_id__delete: {
    parameters: {
      path: {
        workspace_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Workspace
   * @description **Memperbarui metadata *workspace* (misalnya, nama atau ikon).**
   *
   * Hanya field yang disediakan di *payload* yang akan diperbarui.
   *
   * **Keamanan:** Memerlukan peran **Admin** dalam *workspace* tersebut.
   */
  update_workspace_api_v1_workspaces__workspace_id__patch: {
    parameters: {
      path: {
        workspace_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkspaceUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Workspace"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Workspace Members
   * @description Mengambil daftar semua anggota yang terdaftar di 'WorkspaceMembers'.
   *
   * Keamanan:
   * Hanya anggota yang sudah ada di workspace yang dapat melihat
   * daftar anggota lainnya.
   */
  get_members_of_workspace_api_v1_workspace_members__get: {
    parameters: {
      query: {
        workspace_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["WorkspaceMemberResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Invite Member to Workspace
   * @description Mengirim undangan (invite) ke pengguna baru (via Email) atau
   * pengguna yang sudah ada (via User ID).
   *
   * Fitur (Logika "Invite-Only"):
   * Endpoint ini TIDAK menambahkan pengguna secara langsung.
   * Ini membuat entri 'pending' di tabel 'WorkspaceInvitations'.
   * Pengguna yang diundang harus menerima undangan ini.
   *
   * Keamanan:
   * - Hanya 'admin' workspace yang dapat mengirim undangan.
   * - Rate limiting per user (admin): 50 undangan per jam
   * - Rate limiting per workspace: 100 undangan per jam
   * - Rate limiting per email: 5 undangan per jam
   *   (mencegah spam/harassment)
   */
  invite_member_to_workspace_api_v1_workspace_members__post: {
    parameters: {
      query: {
        workspace_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkspaceMemberInviteOrAdd"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Member Role
   * @description Memperbarui role dari anggota yang SUDAH ADA di 'WorkspaceMembers'.
   *
   * Keamanan:
   * Hanya 'admin' yang bisa mengubah role.
   * Fallback: Mencegah 'owner' diturunkan rolenya.
   */
  update_member_role_api_v1_workspace_members__user_id_to_update__patch: {
    parameters: {
      query: {
        workspace_id: string;
      };
      path: {
        user_id_to_update: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkspaceMemberUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Remove Member
   * @description Mengeluarkan (remove) anggota dari 'WorkspaceMembers'.
   *
   * Keamanan:
   * Hanya 'admin' yang bisa mengeluarkan anggota.
   * Fallback: Mencegah 'owner' mengeluarkan dirinya sendiri.
   */
  remove_member_from_workspace_api_v1_workspace_members__user_id_to_remove__delete: {
    parameters: {
      query: {
        workspace_id: string;
      };
      path: {
        user_id_to_remove: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
